### ISSUE TITLE
Formatting creating lines longer than 100 characters

### ISSUE THREAD

**Issue by liutikas** [facebook/ktfmt#407] opened 2023-06-21 23:25 UTC
# Repro steps

```bash
java  -cp /ssd/ssd5/androidx-main/prebuilts/androidx/external/com/facebook/ktfmt/0.44/ktfmt-0.44.jar:..all.jars com.facebook.ktfmt.cli.Main --kotlinlang-style myfile.kt
```

- Try to format the following file:
```kotlin
package androidx.build.lint

import com.android.tools.lint.detector.api.Category
import com.android.tools.lint.detector.api.Detector
import com.android.tools.lint.detector.api.Implementation
import com.android.tools.lint.detector.api.Issue
import com.android.tools.lint.detector.api.Scope
import com.android.tools.lint.detector.api.Severity

class BanConcurrentHashMap : Detector(), Detector.UastScanner {

    companion object {
        val ISSUE = Issue.create(
            "BanConcurrentHashMap",
            "ConcurrentHashMap usage is not allowed",
            "ConcurrentHashMap has an issue on Android’s Lollipop release that can lead to lost" +
                " updates under thread contention.",
            Category.CORRECTNESS, 5, Severity.ERROR,
            Implementation(BanConcurrentHashMap::class.java, Scope.JAVA_FILE_SCOPE)
        )
    }
}
```

# Expected
Code is formatted and no line is longer than 100 characters

# Actual
Formatter splits the string in such a way that one line is longer than 100 characters.

Actual output:
```kotlin
package androidx.build.lint

import com.android.tools.lint.detector.api.Category
import com.android.tools.lint.detector.api.Detector
import com.android.tools.lint.detector.api.Implementation
import com.android.tools.lint.detector.api.Issue
import com.android.tools.lint.detector.api.Scope
import com.android.tools.lint.detector.api.Severity

class BanConcurrentHashMap : Detector(), Detector.UastScanner {

    companion object {
        val ISSUE =
            Issue.create(
                "BanConcurrentHashMap",
                "ConcurrentHashMap usage is not allowed",
                "ConcurrentHashMap has an issue on Android’s Lollipop release that can lead to lost" +
                    " updates under thread contention.",
                Category.CORRECTNESS,
                5,
                Severity.ERROR,
                Implementation(BanConcurrentHashMap::class.java, Scope.JAVA_FILE_SCOPE)
            )
    }
}
```

**Comment by liutikas** [comment] 2023-06-21 23:30
As far as I can tell that's not WAI as [`DEFAULT_MAX_WIDTH: Int = 100`](https://github.com/facebook/ktfmt/blob/main/core/src/main/java/com/facebook/ktfmt/format/FormattingOptions.kt#L60)

**Comment by cgrushko** [comment] 2023-06-22 18:43
hmm, this likely happens because we put a non-breakable space between the string and the `+`.

**Comment by davidtorosyan** [comment] 2023-06-24 17:37
I'm on mobile so I can't count the column lengths well, what would be the preferred format?

In general I think we can't guarantee the limit to be respected in *all* cases, but we could probably improve it here.

**Comment by cgrushko** [comment] 2023-06-25 07:31
The plus sign should be on the next line IMO.

**Comment by hick209** [comment] 2023-09-15 17:07
> The plus sign should be on the next line IMO.

Unless we wrap it in parenthesis, this is not something we can do @cgrushko, as the result will not compile.
See [this example](https://pl.kotl.in/Hkq--CyDg)

@liutikas basically this happens because we don't break up strings. We could introduce logic to break a string, but that's not on our roadmap. You can try to implement that if you feel adventurous.

In other words this is working as intended, therefore I'm closing the issue. Feel free to reopen if you have more comments or if you decide to work on the PR to "fix" this.

**Closed by hick209** 2023-09-15 17:07 UTC
